spring:
  datasource:
    url: jdbc:mysql://localhost:8889/university_db?useSSL=false
    username: root
    password: root

  #JPA Settings
  jpa.hibernate.ddl_auto: update
  #jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
