spring:
  main.allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:8889/university_db?useSSL=false
    username: root
    password: root

  #JPA Settings
  jpa.hibernate.ddl_auto: update
  # Filters chain
  security:
    filter:
      order=10:

